use_frameworks!

platform :ios, '9.0'

target 'ZPDSegmentSlider_Example' do
  pod 'ZPDSegmentSlider', :path => '../'

  target 'ZPDSegmentSlider_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
